### ISSUE TITLE
Error checking fastq-multx version

### ISSUE THREAD

**Issue by lparsons** [hepcat72/htseq2multx#2]
Line 536 seems to be generating an error on my system.

https://github.com/hepcat72/htseq2multx/blob/916e9aa05fccf389c28aefc22e4742a59ff19211/htseq2multx.pl#L536

```
sh: 1: Syntax error: Bad fd number

The following extra and modified options apply specifically to the htseq2multx.pl wrapper (as opposed to barcode_splitter).

optional arguments:
  -h, --help            Supply twice to show this message and exit.
  --version             Supply once to get the barcode_splitter version that
                        this wrapper emulates.  Supply twice to get a more
                        verbose version of the barcode_splitter version that
                        this wrapper emulates and the version of this wrapper.

configuration arguments:
  --fastq-multx PATH    Path to the fastq-multx installation.  Default is to use
                        the PATH in the user's environment.
  --debug               Supply this flag to output the fastq-multx command on
                        standard error and not delete the temporary barcode
                        file.
ERROR: The fastq-multx executable appears to not be fastq-multx according to the first 2 lines of its usage.  Use the --fastq-multx option described above to supply fastq-multx.
```

**Comment by lparsons** [comment]
I'm not sure that all those redirects are needed, and they don't all seem to be portable to `sh`, but this seems simpler and works (at least in my case):
```perl
my $output  = `($fastq_multx 2>&1 ) | head -n 2`; 
```

**Comment by hepcat72** [comment]
> I'm not sure that all those redirects are needed, and they don't all seem to be portable to `sh`, but this seems simpler and works (at least in my case):
> 
> ```perl
> my $output  = `($fastq_multx 2>&1 ) | head -n 2`; 
> ```

Yeah. I always forget the merge stdout/err syntax. I figured all that probably wasn't necessary, but ATT, I didn't bother doing a second google search.

**Comment by hepcat72** [comment]
This is addressed in the current PR.  Though please re-open if your tests show it's not fixed.
