### ISSUE TITLE
Setup continuous integration to run tests

### ISSUE THREAD

**Issue by lparsons** [hepcat72/htseq2multx#3]
It would be nice to have the tests automated in some continuous integration system, GitHub actions, Travis, CircleCI, etc.

* GitHub actions - [Setup a Perl environment](https://github.com/marketplace/actions/setup-perl-environment)
* Travis - [Building a Perl Project](https://docs.travis-ci.com/user/languages/perl/)
* CircleCI - [Perl is supported](https://circleci.com/docs/2.0/demo-apps/), but no demo just yet

**Comment by hepcat72** [comment]
This is implemented and merged in #6.
